version: '3.5'
services:

  connector_maxis:
    build: .
    restart: "always"
    image: "connector_maxis"
    command: "./entrypoint.sh"
    volumes:
      - ./:/code
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8088:8088"
    network_mode: host

  rabbitmq:
    image: rabbitmq:3-management
    restart: "always"
    ports:
     - "15672:15672"
     - "5672:5672"
    network_mode: host

  flower:
    image: mher/flower
    restart: "always"
    network_mode: host

